<Project>
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WindowsTargetFramework>net10.0-windows10.0.26100.0</WindowsTargetFramework>
    <Version>2.0.0</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <FileVersion>$(Version)</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <PinnedWindowsSdkBuildToolsVersion>10.0.26100.8249</PinnedWindowsSdkBuildToolsVersion>
    <DebugSymbols Condition="'$(Configuration)' == 'Release'">false</DebugSymbols>
    <DebugType Condition="'$(Configuration)' == 'Release'">None</DebugType>
  </PropertyGroup>
</Project>
