//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (StronglyTypedResourceBuilder pattern).
//     Manual changes to this file may be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SymlinkCreator.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   NOTE: Keep this class and its members PUBLIC so that WPF {x:Static}
    ///   references can be resolved at runtime. If you regenerate this file with
    ///   the ResXFileCodeGenerator, make sure the resource "Access Modifier"
    ///   is set to Public.
    /// </summary>
    public class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        public Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp =
                        new global::System.Resources.ResourceManager(
                            "SymlinkCreator.Properties.Resources",
                            typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string WindowTitleFormat
        {
            get { return ResourceManager.GetString("WindowTitleFormat", resourceCulture); }
        }

        public static string SourceFileOrFolderListLabel
        {
            get { return ResourceManager.GetString("SourceFileOrFolderListLabel", resourceCulture); }
        }

        public static string AddFilesButton
        {
            get { return ResourceManager.GetString("AddFilesButton", resourceCulture); }
        }

        public static string AddFilesButtonToolTip
        {
            get { return ResourceManager.GetString("AddFilesButtonToolTip", resourceCulture); }
        }

        public static string AddFoldersButton
        {
            get { return ResourceManager.GetString("AddFoldersButton", resourceCulture); }
        }

        public static string AddFoldersButtonToolTip
        {
            get { return ResourceManager.GetString("AddFoldersButtonToolTip", resourceCulture); }
        }

        public static string RemoveSelectedButton
        {
            get { return ResourceManager.GetString("RemoveSelectedButton", resourceCulture); }
        }

        public static string RemoveSelectedButtonToolTip
        {
            get { return ResourceManager.GetString("RemoveSelectedButtonToolTip", resourceCulture); }
        }

        public static string ClearListButton
        {
            get { return ResourceManager.GetString("ClearListButton", resourceCulture); }
        }

        public static string ClearListButtonToolTip
        {
            get { return ResourceManager.GetString("ClearListButtonToolTip", resourceCulture); }
        }

        public static string DestinationPathLabel
        {
            get { return ResourceManager.GetString("DestinationPathLabel", resourceCulture); }
        }

        public static string BrowseButton
        {
            get { return ResourceManager.GetString("BrowseButton", resourceCulture); }
        }

        public static string UseRelativePathCheckBox
        {
            get { return ResourceManager.GetString("UseRelativePathCheckBox", resourceCulture); }
        }

        public static string UseRelativePathCheckBoxToolTip
        {
            get { return ResourceManager.GetString("UseRelativePathCheckBoxToolTip", resourceCulture); }
        }

        public static string RetainScriptFileCheckBox
        {
            get { return ResourceManager.GetString("RetainScriptFileCheckBox", resourceCulture); }
        }

        public static string RetainScriptFileCheckBoxToolTip
        {
            get { return ResourceManager.GetString("RetainScriptFileCheckBoxToolTip", resourceCulture); }
        }

        public static string HideSuccessfulOperationDialogCheckBox
        {
            get { return ResourceManager.GetString("HideSuccessfulOperationDialogCheckBox", resourceCulture); }
        }

        public static string HideSuccessfulOperationDialogCheckBoxToolTip
        {
            get { return ResourceManager.GetString("HideSuccessfulOperationDialogCheckBoxToolTip", resourceCulture); }
        }

        public static string CreateSymlinksButton
        {
            get { return ResourceManager.GetString("CreateSymlinksButton", resourceCulture); }
        }

        public static string AboutButton
        {
            get { return ResourceManager.GetString("AboutButton", resourceCulture); }
        }

        public static string AboutWindowTitle
        {
            get { return ResourceManager.GetString("AboutWindowTitle", resourceCulture); }
        }

        public static string AdminWarningMessageFormat
        {
            get { return ResourceManager.GetString("AdminWarningMessageFormat", resourceCulture); }
        }

        public static string WarningDialogTitle
        {
            get { return ResourceManager.GetString("WarningDialogTitle", resourceCulture); }
        }

        public static string ErrorDialogTitle
        {
            get { return ResourceManager.GetString("ErrorDialogTitle", resourceCulture); }
        }

        public static string NoSourceItemsErrorMessage
        {
            get { return ResourceManager.GetString("NoSourceItemsErrorMessage", resourceCulture); }
        }

        public static string DestinationPathEmptyErrorMessage
        {
            get { return ResourceManager.GetString("DestinationPathEmptyErrorMessage", resourceCulture); }
        }

        public static string ExecutionCompletedMessage
        {
            get { return ResourceManager.GetString("ExecutionCompletedMessage", resourceCulture); }
        }

        public static string DoneDialogTitle
        {
            get { return ResourceManager.GetString("DoneDialogTitle", resourceCulture); }
        }

        public static string AboutDeveloperMessage
        {
            get { return ResourceManager.GetString("AboutDeveloperMessage", resourceCulture); }
        }

        public static string VisitDeveloperWebsiteText
        {
            get { return ResourceManager.GetString("VisitDeveloperWebsiteText", resourceCulture); }
        }

        public static string OkButton
        {
            get { return ResourceManager.GetString("OkButton", resourceCulture); }
        }

        public static string FailedToOpenLinkMessageFormat
        {
            get { return ResourceManager.GetString("FailedToOpenLinkMessageFormat", resourceCulture); }
        }

        public static string DestinationPathDoesNotExistErrorMessage
        {
            get { return ResourceManager.GetString("DestinationPathDoesNotExistErrorMessage", resourceCulture); }
        }

        public static string SymlinkScriptFailedErrorMessage
        {
            get { return ResourceManager.GetString("SymlinkScriptFailedErrorMessage", resourceCulture); }
        }
    }
}
